name: sax
channels:
  - conda-forge
  - fastai
dependencies:
  - make
  - patch
  - suitesparse
  - python
  - pip
  - black
  - bokeh
  - build
  - bump2version
  - fastcore
  - h5py
  - ipykernel
  - ipympl
  - ipywidgets
  - jupyterlab
  - matplotlib
  - natsort
  - nbdev<2
  - nbstripout
  - networkx
  - numpy
  - pandas
  - papermill
  - pre-commit
  - pyright
  - pytables
  - pytest
  - pyyaml
  - scipy
  - shapely
  - tqdm
  - twine
  - typing-extensions
  - jupyter-book
  - pip:
    - flax
    - jax
    - jaxlib
    - tmm
    - sax==0.7.2
